server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_02?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jiangnan0711
    druid:
      max-active: 20
      min-idle: 2
      initial-size: 2
      max-wait: 10000

# Mybatis Plus 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.echo.cloud.entity

